version: "3.4"

services:
  redis:
    container_name: redis
    build: redis/
    restart: always

  app:
    container_name: app
    build: .
    restart: always
    depends_on:
      - redis

  nginx:
    container_name: nginx
    build: nginx/
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app